# Installation

In [1]:
!pip install chainladder

Collecting chainladder
  Downloading chainladder-0.8.18-py3-none-any.whl (1.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 17.5 MB/s eta 0:00:00
Requirement already satisfied: pandas>=0.23 in /usr/local/lib/python3.10/dist-packages (from chainladder) (1.5.3)
Requirement already satisfied: scikit-learn>=0.23 in /usr/local/lib/python3.10/dist-packages (from chainladder) (1.2.2)
Requirement already satisfied: numba>0.54 in /usr/local/lib/python3.10/dist-packages (from chainladder) (0.58.1)
Collecting sparse>=0.9 (from chainladder)
  Downloading sparse-0.15.1-py2.py3-none-any.whl (116 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 116.3/116.3 kB 13.5 MB/s eta 0:00:00
Requirement already satisfied: matplotlib in /usr/local/lib/python3.10/dist-packages (from chainladder) (3.7.1)
Collecting dill (from chainladder)
  Downloading dill-0.3.8-py3-none-any.whl (116 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 116.3/116.3 kB 14.2 MB/s eta 0:00:00
Requirement already satisfied: patsy in /usr/local/lib/python3.10/dist-packages (from chainladder) (0.5.6)
Requirement already satisfied: llvmlite<0.42,>=0.41.0dev0 in /usr/local/lib/python3.10/dist-packages (from numba>0.54->chainladder) (0.41.1)
Requirement already satisfied: numpy<1.27,>=1.22 in /usr/local/lib/python3.10/dist-packages (from numba>0.54->chainladder) (1.25.2)
Requirement already satisfied: python-dateutil>=2.8.1 in /usr/local/lib/python3.10/dist-packages (from pandas>=0.23->chainladder) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas>=0.23->chainladder) (2023.4)
Requirement already satisfied: scipy>=1.3.2 in /usr/local/lib/python3.10/dist-packages (from scikit-learn>=0.23->chainladder) (1.11.4)
Requirement already satisfied: joblib>=1.1.1 in /usr/local/lib/python3.10/dist-packages (from scikit-learn>=0.23->chainladder) (1.3.2)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from scikit-learn>=0.23->chainladder) (3.4.0)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib->chainladder) (1.2.0)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.10/dist-packages (from matplotlib->chainladder) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib->chainladder) (4.50.0)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib->chainladder) (1.4.5)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib->chainladder) (24.0)
Requirement already satisfied: pillow>=6.2.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib->chainladder) (9.4.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib->chainladder) (3.1.2)
Requirement already satisfied: six in /usr/local/lib/python3.10/dist-packages (from patsy->chainladder) (1.16.0)
Installing collected packages: dill, sparse, chainladder
Successfully installed chainladder-0.8.18 dill-0.3.8 sparse-0.15.1

# Import libraries

In [4]:
import chainladder as cl
import pandas as pd

In [17]:
pd.set_option('display.max_columns', None)

# Read data

In [19]:
data_df = pd.read_csv('data.csv')
data_df.head()

,ClaimNo,AccidentDate,ReportDate,CloseDate,Status,Paid,Outstanding,Incurred
0,38138,10/1/2017,3/21/2017,7/24/2017,CLOSED,4533.115817,0,4533.115817
1,38140,8/1/2017,2/20/2017,7/13/2017,CLOSED,2984.268178,0,2984.268178
2,38141,2/1/2017,1/7/2017,9/7/2017,CLOSED,7197.433065,0,7197.433065
3,38142,7/1/2017,1/23/2017,2/7/2017,CLOSED,7000.000000,0,7000.000000
4,38143,15/1/2017,5/17/2017,7/24/2017,CLOSED,2924.542595,0,2924.542595

# Calculate the triangle with incurred loss

In [22]:
tri = cl.Triangle(data=data_df,
            origin='AccidentDate', development='ReportDate',
            columns='Incurred', cumulative=True)

/usr/local/lib/python3.10/dist-packages/chainladder/core/base.py:248: UserWarning: Parsing dates in DD/MM/YYYY format when dayfirst=False (the default) was specified. This may lead to inconsistently parsed dates! Specify a format to ensure consistent parsing.
  arr = dict(zip(datetime_arg, pd.to_datetime(**item)))
/usr/local/lib/python3.10/dist-packages/chainladder/core/base.py:106: UserWarning:
                Observations with development before
                origin start have been removed.
  warnings.warn(

# Show the triangle

In [23]:
tri

                    1              2              3              4              5              6             7             8             9             10  11  12
2017-01   69822.892168  198630.913129  188101.425531  103105.913933  111786.721399   72572.603595  45177.368050  39037.282539  28181.203359           NaN NaN NaN
2017-02   85125.421500  273790.896533  143326.368077   87281.692171   42994.940946  106360.058135  21812.134524  31068.890593           NaN  37413.544644 NaN NaN
2017-03   75783.219675  186916.568442  189901.821916   97355.105421   54936.529285   53339.267798  25110.568780  17308.875192  17185.499359   4666.609234 NaN NaN
2017-04   74679.012616  203659.855254  103622.641007  106460.457704   39537.335171   44861.681918  29065.405528  37094.472141           NaN           NaN NaN NaN
2017-05  111740.616208  201488.741224   93298.045337  134779.769420   71465.004859   43890.480908  11426.515526           NaN           NaN           NaN NaN NaN
2017-06   77980.862393   96061.089114   85758.632688   45149.936898   39728.529841   13553.643970           NaN           NaN           NaN           NaN NaN NaN
2017-07   53759.326067  126483.029147   65945.817409   40338.791324    4699.625426   14554.443960           NaN           NaN           NaN           NaN NaN NaN
2017-08   45489.434820   65660.358913   78147.661179   39441.849121   11582.588580            NaN           NaN           NaN           NaN           NaN NaN NaN
2017-09   50010.754503   86612.212288   65770.188162            NaN            NaN            NaN           NaN           NaN           NaN           NaN NaN NaN
2017-10   27747.025305   59272.423719   13347.258310            NaN            NaN            NaN           NaN           NaN           NaN           NaN NaN NaN
2017-11   18057.709476            NaN            NaN            NaN            NaN            NaN           NaN           NaN           NaN           NaN NaN NaN
2017-12   10748.025150            NaN            NaN            NaN            NaN            NaN           NaN           NaN           NaN           NaN NaN NaN